package grafica;

import logica.*;

public class ficha extends javax.swing.JFrame {

    

    /**
     * Creates new form ficha
     */
    public ficha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_genero = new javax.swing.ButtonGroup();
        grupo_materia = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GEN_MAS = new javax.swing.JRadioButton();
        GEN_FEM = new javax.swing.JRadioButton();
        GEN_OTRO = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        año_curso = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        mat_progr = new javax.swing.JCheckBox();
        mat_bd = new javax.swing.JCheckBox();
        mat_sist = new javax.swing.JCheckBox();
        mat_taller = new javax.swing.JCheckBox();
        btn_guardar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATOS ALUMNOS");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("APELLIDO");

        jLabel4.setText("GENERO");

        grupo_genero.add(GEN_MAS);
        GEN_MAS.setText("MASCULINO");
        GEN_MAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GEN_MASActionPerformed(evt);
            }
        });

        grupo_genero.add(GEN_FEM);
        GEN_FEM.setText("FEMENINO");

        grupo_genero.add(GEN_OTRO);
        GEN_OTRO.setText("OTRO");
        GEN_OTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GEN_OTROActionPerformed(evt);
            }
        });

        jLabel5.setText("AÑO QUE CURSA");

        año_curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero", "Segundo", "Tercero" }));
        año_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                año_cursoActionPerformed(evt);
            }
        });

        jLabel6.setText("MATERIA FAVORITA");

        grupo_materia.add(mat_progr);
        mat_progr.setText("Programación");
        mat_progr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat_progrActionPerformed(evt);
            }
        });

        grupo_materia.add(mat_bd);
        mat_bd.setText("Base de datos");
        mat_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat_bdActionPerformed(evt);
            }
        });

        grupo_materia.add(mat_sist);
        mat_sist.setText("Sistema Operativos");
        mat_sist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat_sistActionPerformed(evt);
            }
        });

        grupo_materia.add(mat_taller);
        mat_taller.setText("Taller");
        mat_taller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat_tallerActionPerformed(evt);
            }
        });

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(GEN_MAS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GEN_FEM)
                                .addGap(18, 18, 18)
                                .addComponent(GEN_OTRO))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(año_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mat_progr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mat_bd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mat_sist)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mat_taller))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_apellido))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(GEN_MAS)
                    .addComponent(GEN_FEM)
                    .addComponent(GEN_OTRO))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(año_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mat_progr)
                    .addComponent(mat_bd)
                    .addComponent(mat_sist)
                    .addComponent(mat_taller))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_guardar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GEN_OTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GEN_OTROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GEN_OTROActionPerformed

    private void año_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_año_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_año_cursoActionPerformed

    private void GEN_MASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GEN_MASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GEN_MASActionPerformed

    private void mat_progrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat_progrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat_progrActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed

    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed

    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
       alumnos c = new alumnos();
        c.setNombre(txt_nombre.getText());
        c.setApellido(txt_apellido.getText());
        
        //Opcion de genero
        
        String genero = null;
        c.setGenero(genero);
        if(GEN_MAS.isSelected()){
            genero = "Masculino";
                }
        if(GEN_FEM.isSelected()){
            genero = "Femenino";
                }
        if(GEN_OTRO.isSelected()){
            genero = "Otro";
                }
        
        //Opcion de año de curso
        String curso = null;
        c.setCurso(curso);
        curso = (String) año_curso.getSelectedItem();
        
        
        //Opcion de materias
                
        String materia = null;
       
        if(mat_progr.isSelected()){
            materia = "Programación";
            }
        if(mat_bd.isSelected()){
            materia = "Base de datos";
            }
        if(mat_sist.isSelected()){
            materia = "Sistema operativo";
            }
        if(mat_taller.isSelected()){
            materia = "Taller";
            }
        
        
        //Agregar alumnos
        
     
        
        
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void mat_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat_bdActionPerformed

    private void mat_sistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat_sistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat_sistActionPerformed

    private void mat_tallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat_tallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat_tallerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ficha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton GEN_FEM;
    private javax.swing.JRadioButton GEN_MAS;
    private javax.swing.JRadioButton GEN_OTRO;
    private javax.swing.JComboBox<String> año_curso;
    private javax.swing.JButton btn_guardar;
    private javax.swing.ButtonGroup grupo_genero;
    private javax.swing.ButtonGroup grupo_materia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox mat_bd;
    private javax.swing.JCheckBox mat_progr;
    private javax.swing.JCheckBox mat_sist;
    private javax.swing.JCheckBox mat_taller;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

}
